gui:
  border: rounded
  theme:
    activeBorderColor:
      - "#5ef1ff"
    inactiveBorderColor:
      - "#7b8496"
    optionsTextColor:
      - "#3c4048"
    searchingActiveBorderColor:
      - "#ff5ef1"
    selectedLineBgColor:
      - "#3c4048" # set to `default` to have no background colour
    selectedRangeBgColor:
      - default
    cherryPickedCommitBgColor:
        - "#3c4048"
    cherryPickedCommitFgColor:
        - "#ff5ea0"
    unstagedChangesColor:
        - "#ffbd5e"
    defaultFgColor:
        - "#ffffff"
  showFileTree: true # for rendering changes files in a tree format
  showListFooter: false # for seeing the '5 of 20' message in list panels
  showRandomTip: false
  showBottomLine: false # for hiding the bottom information line (unless it has important information to tell you)
  showCommandLog: false
  showIcons: false # deprecated: use nerdFontsVersion instead
  nerdFontsVersion: "3" # nerd fonts version to use ("2" or "3"); empty means don't show nerd font icons
os:
  editCommand: 'nvim'
confirmOnQuit: true
disableStartupPopups: true
notARepository: 'skip' # one of: 'prompt' | 'create' | 'skip'
