#!/bin/bash

# This is a demo config to showcase some of the most important commands.
# It is meant to be changed and configured, as it is intentionally kept sparse.
# For a (much) more advanced configuration example see my dotfiles:
# https://github.com/FelixKratz/dotfiles

PLUGIN_DIR="$CONFIG_DIR/plugins"
ITEMS_DIR="$CONFIG_DIR/items"

source "$CONFIG_DIR/colors.sh" # Loads all defined colors

##### Bar Appearance #####
# Configuring the general appearance of the bar.
# These are only some of the options available. For all options see:
# https://felixkratz.github.io/SketchyBar/config/bar
# If you are looking for other colors, see the color picker:
# https://felixkratz.github.io/SketchyBar/config/tricks#color-picker

sketchybar --bar height=24        \
                 blur_radius=30   \
                 position=top     \
                 sticky=off       \
                 padding_left=10  \
                 padding_right=10 \
                 color=$SEMITRANSPARENT

##### Changing Defaults #####
# We now change some default values, which are applied to all further items.
# For a full list of all available item properties see:
# https://felixkratz.github.io/SketchyBar/config/items

default=(
  icon.font="SF Pro:Semibold:13.0"
  icon.color=$WHITE                
  label.font="SF Pro:Semibold:13.0"
  label.color=$WHITE               
  background.color=$TRANSPARENT
  background.corner_radius=5       
  background.height=20
  padding_left=0
  padding_right=0
  label.padding_left=4             
  label.padding_right=10           
  icon.padding_left=10             
  icon.padding_right=4
)
sketchybar --default "${default[@]}"

##### Adding Left Items #####
# source $ITEMS_DIR/apple.sh
source $ITEMS_DIR/spaces.sh
source $ITEMS_DIR/front_app.sh

##### Adding Right Side Of Notch Items #####
# source $ITEMS_DIR/media.sh

##### Adding Right Items #####
source $ITEMS_DIR/calendar.sh
source $ITEMS_DIR/battery.sh
# source $ITEMS_DIR/keyboard.sh
# source $ITEMS_DIR/volume.sh
# source $ITEMS_DIR/cpu.sh
# source $ITEMS_DIR/brew.sh

##### Force all scripts to run the first time (never do this in a script) #####
sketchybar --update
