#!/usr/bin/env sh

#   ██╗   ██╗ █████╗ ██████╗  █████╗ ██╗
#   ╚██╗ ██╔╝██╔══██╗██╔══██╗██╔══██╗██║
#    ╚████╔╝ ███████║██████╔╝███████║██║
#     ╚██╔╝  ██╔══██║██╔══██╗██╔══██║██║
#      ██║   ██║  ██║██████╔╝██║  ██║██║
#      ╚═╝   ╚═╝  ╚═╝╚═════╝ ╚═╝  ╚═╝╚═╝
#

# for this to work you must configure sudo such that
# it will be able to run the command without password

yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

# debugger
# run to solve "a password is required" problem:
# echo "$(whoami) ALL=(ALL) NOPASSWD: $(which yabai)" | sudo tee /etc/sudoers.d/yabai
yabai -m config debug_output on

# global settings
yabai -m config active_window_opacity 1.0

yabai -m config auto_balance on

yabai -m config normal_window_opacity 0.94

yabai -m config mouse_modifier alt
yabai -m config mouse_action1 move
yabai -m config mouse_action2 resize
yabai -m config mouse_follows_focus on

yabai -m config split_ratio 0.50

yabai -m config window_animation_duration 0.1
yabai -m config window_opacity on
yabai -m config window_placement second_child
yabai -m config window_shadow on

# general space settings
yabai -m config layout bsp

# can use Übersicht to create custom status bars
yabai -m config external_bar main:0:0

yabai -m config top_padding 8
yabai -m config right_padding 8
yabai -m config bottom_padding 8
yabai -m config left_padding 8

yabai -m config window_gap 8

# space 1: communication
yabai -m space 1 --layout stack
yabai -m rule --add app="Mattermost" space=^1
yabai -m rule --add app="Telegram" space=^1
yabai -m rule --add app="WhatsApp*." space=^1

# space 2: db and rest test
yabai -m space 2 --layout stack
yabai -m rule --add app="DBeaver" space=^2
yabai -m rule --add app="Postman" space=^2

# space 3: terminals
yabai -m rule --add app="iTerm2" space=^3
yabai -m rule --add app="kitty" space=^3

# space 4: intellij development
yabai -m rule --add app="IntelliJ IDEA" space=^4

# space 5: browser
yabai -m rule --add app="Google Chrome" space=^5

# things which create floating children
yabai -m rule --add app="AlDente" manage=off
yabai -m rule --add app="App Store" manage=off
yabai -m rule --add app="Cursor Pro" manage=off
yabai -m rule --add app="Finder" manage=off
yabai -m rule --add app="iStat Menus" manage=off mouse_follows_focus=off
yabai -m rule --add app="JetBrains Toolbox" manage=off mouse_follows_focus=off
yabai -m rule --add app="Logi Options" manage=off mouse_follows_focus=off
yabai -m rule --add app="Notes" manage=off
yabai -m rule --add app="System Settings" manage=off
yabai -m rule --add app="Tips" manage=off

# dbeaver
yabai -m rule --add app="DBeaver" title="Connect*.|Version*.|.*settings" manage=off

# make JetBrains products popup windows float
yabai -m rule --add app="IntelliJ IDEA" title="JetBrains Toolbox" manage=off mouse_follows_focus=off
yabai -m rule --add app="IntelliJ IDEA" title=".*Run*.|Choose*.|Delete*.|Generate*.|.*Git*.|New*.|Move*.|.*Structure|Preferences*.|Plugin*.|Rename*.|Select*.|Settings*.|.*Toolbar*.|.*Welcome*." manage=off
